name: Build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Upload portable executable
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: target/release/alacritty.exe
